language: python

branches:
  only:
    - master

env:
  - DOCKER_COMPOSE_VERSION=1.25.5
  - DOCKER_ENGINE_VERSION=19.03.8~ce~3-0~ubuntu


python:
  - "3.8"

sudo: required

services:
  - docker

before_install:
  - sudo apt update
  - sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt update
  - sudo apt-cache madison docker-ce
  - sudo apt-get install docker-ce=${DOCKER_ENGINE_VERSION}
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

install:
  - cd backend
  - pip install -r requirements.prod

script:
  - python -m unittest tests/test_main.py
  - cd ..
  - docker-compose build